Fixes SUPPRESS_ERROR_PAGE warning after webview_flutter_android upgrade
pichillilorenzo/flutter_inappwebview pull request #2182
Opened 2024-06-15 08:56 UTC by Manuito83

## Connection with issue(s)

Resolve issue #2150

## Testing and Review Notes

The SUPPRESS_ERROR_PAGE feature was discontinued according to [this](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:webkit/webkit/src/main/java/androidx/webkit/WebViewFeature.java;bpv=1;bpt=0;drc=071a5be0e7583c5ded85015ff94dc2ab7a7f0d62;dlc=bf75ca82f3a2182d583436a85f466396cf2f4f72) change in Webkit's WebViewFeature.java.

The recent upgrade of webkit to 1.10.0 in webview_flutter_android causes the webview to be null.

This suppresses references to SUPPRESS_ERROR_PAGE.

2024-06-17 08:39 UTC, EArminjon commented
How override error pages if we no longer have disableDefaultErrorPage ?

2024-06-17 09:23 UTC, Manuito83 commented
@EArminjon I can't say. This was a featured that was never launched in webkit:

> _Remove unlaunched suppressErrorPage API_
> _Removing this abandoned API, which was never launched._

This is a [change](https://cs.android.com/androidx/platform/frameworks/support/+/071a5be0e7583c5ded85015ff94dc2ab7a7f0d62) performed in WebViewFeature.java almost a year ago.

2024-07-03 15:13 UTC, subzero911 commented
I need this fix ASAP, because I have this error.
A webview is just blank.

2024-07-05 02:42 UTC, RaymondGsc commented
@pichillilorenzo I also need this fix, the webview just throw a SUPPRESS_ERROR_PAGE when opening.

2024-07-11 12:40 UTC, Julied5 commented
your code does the trick but the webkit update gets me another error if i open a webview in a new flutter page and i pop it, the app just crashes :
```
E/AndroidRuntime( 4220): java.lang.IncompatibleClassChangeError: Found interface androidx.webkit.ScriptHandler, but class was expected (declaration of 'androidx.webkit.ScriptHandler' appears in /data/app/~~.......
E/AndroidRuntime( 4220): 	at com.pichillilorenzo.flutter_inappwebview_android.types.UserContentController.removeAllPluginScripts(UserContentController.java:310)
```

i guess it is because the webkit version in build.gradle is still in 1.8.0 (where the ScriptHandler is defined as an abstract class) and in the updated webkit (located in webview_flutter_android) the ScriptHandler is an interface, it creates a conflict between the two versions

if i replace with a newer webkit version (in android/build.gradle line 52) it fixes my bug :
```
dependencies {
    implementation 'androidx.webkit:webkit:1.11.0'
    implementation 'androidx.browser:browser:1.6.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
}
```

@Manuito83 can you tell me if you reproduce as well ?

2024-07-11 13:06 UTC, Julied5 commented
yes it also works with 1.10.0 but not with the actual one (1.8.0) defined in flutter_inappwebview_android/android/build.gradle

2024-07-17 19:25 UTC, ndavis-rxss commented
LGTM

2024-07-18 13:03 UTC, tkreuder commented
Does not work for me:

```
  flutter_inappwebview:
    git:
      url: https://github.com/Manuito83/flutter_inappwebview.git
      ref: v6.0.0-fix-suppress-error-page
      path: flutter_inappwebview
```
followed by:

`flutter clean && flutter pub get`

results in the same issue in release mode. Am i doing something wrong here @Manuito83 ?

2024-07-19 09:01 UTC, EArminjon commented
Personally i make the fix different : 

Old code 

```java
if (!WebViewFeature.isFeatureSupported(WebViewFeature.SUPPRESS_ERROR_PAGE) &&
      webView.customSettings.disableDefaultErrorPage) {}
```

New code (as feature no longer supported and so should match 'false')
```java
if (webView.customSettings.disableDefaultErrorPage) {
```

I also updated webkit inside android/build.gradle

```gradle
implementation 'androidx.webkit:webkit:1.11.0'
```

2024-07-19 09:08 UTC, EArminjon requested changes

2024-07-19 09:08 UTC, EArminjon commented on flutter_inappwebview_android/android/src/main/java/com/pichillilorenzo/flutter_inappwebview_android/webview/in_app_webview/InAppWebViewClient.java
> -            webView.customSettings.disableDefaultErrorPage) {
You can just remove !WebViewFeature.isFeatureSupported(WebViewFeature.SUPPRESS_ERROR_PAGE)  and keep the if

2024-07-19 09:08 UTC, EArminjon commented on flutter_inappwebview_android/android/src/main/java/com/pichillilorenzo/flutter_inappwebview_android/webview/in_app_webview/InAppWebViewClientCompat.java
> -    if (!WebViewFeature.isFeatureSupported(WebViewFeature.SUPPRESS_ERROR_PAGE) &&
You can just remove !WebViewFeature.isFeatureSupported(WebViewFeature.SUPPRESS_ERROR_PAGE)  and keep the if

2024-07-19 09:08 UTC, EArminjon commented on flutter_inappwebview_platform_interface/lib/src/platform_webview_feature.dart
Please keep old code format. That make review very hard, didn't see what you have changed.

2024-07-22 03:46 UTC, RaymondGsc commented
> Personally i make the fix different to still support `disableDefaultErrorPage` :
> 
> Old code
> 
> ```java
> if (!WebViewFeature.isFeatureSupported(WebViewFeature.SUPPRESS_ERROR_PAGE) &&
>       webView.customSettings.disableDefaultErrorPage) {}
> ```
> 
> New code (as feature no longer supported and so should match 'false')
> 
> ```java
> if (webView.customSettings.disableDefaultErrorPage) {
> ```
> 
> I also updated webkit inside android/build.gradle
> 
> ```groovy-gradle
> implementation 'androidx.webkit:webkit:1.11.0'
> ```
> 
> I can create a new PR for that.
Please fix it, I need this update ASAP, thx.

2024-07-22 07:19 UTC, EArminjon commented
> > Personally i make the fix different to still support `disableDefaultErrorPage` :
> > Old code
> > ```java
> > if (!WebViewFeature.isFeatureSupported(WebViewFeature.SUPPRESS_ERROR_PAGE) &&
> >       webView.customSettings.disableDefaultErrorPage) {}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > New code (as feature no longer supported and so should match 'false')
> > ```java
> > if (webView.customSettings.disableDefaultErrorPage) {
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I also updated webkit inside android/build.gradle
> > ```
> > implementation 'androidx.webkit:webkit:1.11.0'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I can create a new PR for that.
> 
> Please fix it, I need this update ASAP, thx.

Can you test https://github.com/pichillilorenzo/flutter_inappwebview/pull/2231 ?

2024-07-22 12:50 UTC, ndavis-rxss commented
@pichillilorenzo

2024-07-31 07:25 UTC, RaymondGsc commented
> > > Personally i make the fix different to still support `disableDefaultErrorPage` :
> > > Old code
> > > ```java
> > > if (!WebViewFeature.isFeatureSupported(WebViewFeature.SUPPRESS_ERROR_PAGE) &&
> > >       webView.customSettings.disableDefaultErrorPage) {}
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > New code (as feature no longer supported and so should match 'false')
> > > ```java
> > > if (webView.customSettings.disableDefaultErrorPage) {
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I also updated webkit inside android/build.gradle
> > > ```
> > > implementation 'androidx.webkit:webkit:1.11.0'
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I can create a new PR for that.
> > 
> > 
> > Please fix it, I need this update ASAP, thx.
> 
> Can you test #2231 ?

Yes, I have test #2231 , and

> > > Personally i make the fix different to still support `disableDefaultErrorPage` :
> > > Old code
> > > ```java
> > > if (!WebViewFeature.isFeatureSupported(WebViewFeature.SUPPRESS_ERROR_PAGE) &&
> > >       webView.customSettings.disableDefaultErrorPage) {}
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > New code (as feature no longer supported and so should match 'false')
> > > ```java
> > > if (webView.customSettings.disableDefaultErrorPage) {
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I also updated webkit inside android/build.gradle
> > > ```
> > > implementation 'androidx.webkit:webkit:1.11.0'
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I can create a new PR for that.
> > 
> > 
> > Please fix it, I need this update ASAP, thx.
> 
> Can you test #2231 ?

I have all the code checked, but I wonder how can I test your code on my own device.

2024-08-23 23:40 UTC, jwbrown commented
I implemented
```
dependencies {
    implementation 'androidx.webkit:webkit:1.11.0'
    implementation 'androidx.browser:browser:1.6.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
}
```
in my projects build.gradle but am still getting the  java.lang.IncompatibleClassChangeError

```
[AndroidInAppWebViewWidget] (android) AndroidInAppWebViewWidget calling "dispose" using []
E/AndroidRuntime(10863): FATAL EXCEPTION: main
E/AndroidRuntime(10863): Process: com.example.letts_news, PID: 10863
E/AndroidRuntime(10863): java.lang.IncompatibleClassChangeError: Found interface androidx.webkit.ScriptHandler, but class was expected (declaration of 'androidx.webkit.ScriptHandler' appears in /data/app/~~qjcoDlweDOdhaTmOimMemg==/com.example.letts_news-ubVVtKNAKvjVDbcv-qI7KA==/base.apk)
E/AndroidRuntime(10863): 	at com.pichillilorenzo.flutter_inappwebview_android.types.UserContentController.removeAllPluginScripts(UserContentController.java:309)
E/AndroidRuntime(10863): 	at com.pichillilorenzo.flutter_inappwebview_android.types.UserContentController.dispose(UserContentController.java:470)
E/AndroidRuntime(10863): 	at com.pichillilorenzo.flutter_inappwebview_android.webview.in_app_webview.InAppWebView.dispose(InAppWebView.java:2065)
E/AndroidRuntime(10863): 	at com.pichillilorenzo.flutter_inappwebview_android.webview.in_app_webview.FlutterWebView.dispose(FlutterWebView.java:154)
E/AndroidRuntime(10863): 	at io.flutter.plugin.platform.PlatformViewsController$1.dispose(PlatformViewsController.java:254)
E/AndroidRuntime(10863): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.dispose(PlatformViewsChannel.java:150)
E/AndroidRuntime(10863): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:58)
E/AndroidRuntime(10863): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/AndroidRuntime(10863): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/AndroidRuntime(10863): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/AndroidRuntime(10863): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/AndroidRuntime(10863): 	at android.os.Handler.handleCallback(Handler.java:942)
E/AndroidRuntime(10863): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(10863): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(10863): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(10863): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/AndroidRuntime(10863): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(10863): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(10863): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

```
I've been stuck on this for most of the day so any direction would be appreciated

2024-08-24 06:01 UTC, EArminjon commented
> I implemented
> ```
> dependencies {
>     implementation 'androidx.webkit:webkit:1.11.0'
>     implementation 'androidx.browser:browser:1.6.0'
>     implementation 'androidx.appcompat:appcompat:1.6.1'
>     implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
> }
> ```
> in my projects build.gradle but am still getting the  java.lang.IncompatibleClassChangeError
> 
> ```
> [AndroidInAppWebViewWidget] (android) AndroidInAppWebViewWidget calling "dispose" using []
> E/AndroidRuntime(10863): FATAL EXCEPTION: main
> E/AndroidRuntime(10863): Process: com.example.letts_news, PID: 10863
> E/AndroidRuntime(10863): java.lang.IncompatibleClassChangeError: Found interface androidx.webkit.ScriptHandler, but class was expected (declaration of 'androidx.webkit.ScriptHandler' appears in /data/app/~~qjcoDlweDOdhaTmOimMemg==/com.example.letts_news-ubVVtKNAKvjVDbcv-qI7KA==/base.apk)
> E/AndroidRuntime(10863): 	at com.pichillilorenzo.flutter_inappwebview_android.types.UserContentController.removeAllPluginScripts(UserContentController.java:309)
> E/AndroidRuntime(10863): 	at com.pichillilorenzo.flutter_inappwebview_android.types.UserContentController.dispose(UserContentController.java:470)
> E/AndroidRuntime(10863): 	at com.pichillilorenzo.flutter_inappwebview_android.webview.in_app_webview.InAppWebView.dispose(InAppWebView.java:2065)
> E/AndroidRuntime(10863): 	at com.pichillilorenzo.flutter_inappwebview_android.webview.in_app_webview.FlutterWebView.dispose(FlutterWebView.java:154)
> E/AndroidRuntime(10863): 	at io.flutter.plugin.platform.PlatformViewsController$1.dispose(PlatformViewsController.java:254)
> E/AndroidRuntime(10863): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.dispose(PlatformViewsChannel.java:150)
> E/AndroidRuntime(10863): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:58)
> E/AndroidRuntime(10863): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
> E/AndroidRuntime(10863): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
> E/AndroidRuntime(10863): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
> E/AndroidRuntime(10863): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
> E/AndroidRuntime(10863): 	at android.os.Handler.handleCallback(Handler.java:942)
> E/AndroidRuntime(10863): 	at android.os.Handler.dispatchMessage(Handler.java:99)
> E/AndroidRuntime(10863): 	at android.os.Looper.loopOnce(Looper.java:201)
> E/AndroidRuntime(10863): 	at android.os.Looper.loop(Looper.java:288)
> E/AndroidRuntime(10863): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
> E/AndroidRuntime(10863): 	at java.lang.reflect.Method.invoke(Native Method)
> E/AndroidRuntime(10863): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
> E/AndroidRuntime(10863): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
> 
> ```
> I've been stuck on this for most of the day so any direction would be appreciated
> 

You can test https://github.com/pichillilorenzo/flutter_inappwebview/pull/2231

2024-08-24 11:27 UTC, jwbrown commented
@EArminjon 

Cannot thank you enough, this worked for me.

Strangely i could not just clone and checkout the PR and build - have some weird problems in my flutter config still....   I was however able to patch .pub-cache with the changes and it fixes the problem perfectly.

Again thanks!  how the change is merged into the package


Jim

2024-09-18 16:12 UTC, kassandra-all-win-software commented
> it worked for me and i bumped `implementation 'androidx.webkit:webkit:1.11.0'` in build.gradle:
> 
> pubspec.yaml
> 
> ```
> dependency_overrides:
>   flutter_inappwebview_android:
>     git:
>       url: https://github.com/tkreuder/flutter_inappwebview.git
>       ref: v6.0.0-fix-suppress-error-page
>       path: flutter_inappwebview_android
> ```

It's Works for me

2024-09-20 13:29 UTC, arrrrny commented
@EArminjon @jwbrown @RaymondGsc @ndavis-rxss @tkreuder @Julied5 @Manuito83 @subzero911  Open your PR on the forked project [here](https://github.com/arrrrny/zikzak_inappwebview) and I will merge.  There is a new package now. [zikzak_inappwebview](https://pub.dev/packages/zikzak_inappwebview)

2024-09-23 13:07 UTC, pichillilorenzo commented
Released new version 6.1.0 with the fix, thanks!

2024-09-23 13:07 UTC, closed without merging

2024-09-24 06:08 UTC, abdallah-odeh commented
@pichillilorenzo is this update requires to have SDK version 3.5.0 or it might be used on a lower bound? because it's kinda high & not everyone has updated to latest version

```
The current Dart SDK version is 3.4.3.

Because app_namespace depends on flutter_inappwebview >=6.1.0 which requires SDK version >=3.5.0 <4.0.0, version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on flutter_inappwebview: flutter pub add flutter_inappwebview:^6.0.0
```

2024-09-24 07:31 UTC, pichillilorenzo commented
@abdallah-odeh currently the `InAppWebView` widget for MacOS is only supported starting from Flutter version ">=3.24.0" (which is based on Dart 3.5.0)