fixed flutter 3.22.2 compatibility issue
pichillilorenzo/flutter_inappwebview pull request #2209
Opened 2024-07-03 05:54 UTC by weng-deriv

Upon upgrading to flutter 3.22.2, the app is not being built successfully due to the missing proguard rule in flutter_android_inappwebview.

2024-07-03 05:57 UTC, Manuito83 commented
Yet another similar pull request for this...

2024-07-11 00:45 UTC, bsz0206 approved these changes

2024-08-06 15:13 UTC, JoseBarreto1 requested changes
Yet another similar pull request for this...

2024-09-23 13:07 UTC, pichillilorenzo commented
https://github.com/pichillilorenzo/flutter_inappwebview/pull/2231

2024-09-23 13:07 UTC, closed without merging